version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: group-travel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: group_travel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: group-travel-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/group_travel
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - NODE_ENV=production
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm start
      "

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: group-travel-web
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/graphql
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge